version: '3.9'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27055
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: scanalyze_mongo
    command: mongod --port 27055
    ports:
      - "27055:27055"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge