version: '3.9'

services:
  backend:
    build: .
    ports:
      - "9091:8000"
    depends_on:
      - mongo
      - mysql
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27055
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_DB=res_toxval_v96_2
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: scanalyze_mongo
    command: mongod --port 27055
    ports:
      - "27055:27055"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: toxval_mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=res_toxval_v96_2
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mongo_data:
  mysql_data:

networks:
  app-network:
    driver: bridge